### ISSUE TITLE
Don't overlap same hotkeys with different modifiers

### ISSUE THREAD

**Issue by filantus** [btsdev/global_hotkeys#1]
Hi! Can you please tell, it's possible to run only one trigger if hotkeys are same but one have modfier?

For example, now if i have registered hotkeys "w", and "alt + w", and press "alt + w", then both triggers runs.
In that case i want that only "alt + w" trigger has been started.

**Comment by btsdev** [comment]
Hi @filantus, sorry for the late response. I'll have a look when I get a chance and see if I can resolve this issue. 

I realize I should be checking the presence of modifier keys (e.g. ctrl, alt, shift) before settling on a match. Will let you know as soon as this is updated.

**Comment by btsdev** [comment]
This should now be fixed. The code now checks that unwanted modifiers aren't also being pressed when verifying that a hotkey is being pressed or not. Thanks!
