### ISSUE TITLE
[Non-Issue / Question] Prevent function being called on initialization?

### ISSUE THREAD

**Issue by vaylvn** [btsdev/global_hotkeys#10]
Apologies as this (potentially) isn't even an issue,

It appears that when I add the bindings for a hotkey then register the hotkeys, the callback function seems to be called?

Just wondering if that's intentional or perhaps whether I've missed something when registering the bindings.as it seems odd to call the function with no provokation from the user.

Thanks!

**Comment by btsdev** [comment]
Hi @ValonVN0,

If you can provide a sample of the way you're adding and registering (one of) the hotkeys whose callback is being immediately fired on being bound, that would help. (also, maybe a shortened example of one of these callback functions you've defined would help too). Are you sure you're not calling that function elsewhere by chance and have missed it?

In short though, the callback should only be fired when the hotkey is pressed, not when it's registered.

**Comment by vaylvn** [comment]
Thanks for the prompt response!

So I've double checked and there's no instance of calling the function anywhere else fortunately(?), however I can provide a basic example which does print the given "hotkey triggered: test" in the console upon loading up:

```
def triggerHotkey(name):
    print ("HotKey Triggered: " + name)

def establishHotkey():
    try:
        bindings = []
        bindings.append("k", None, triggerHotkey("test"))
        register_hotkeys(bindings)
        start_checking_hotkeys()
    except Exception as e:
        print ("[!] Error loading Custom Hotkeys.")
```

Off topic but github isn't providing the right amount of ` for code blocks by default, weird...

**Comment by btsdev** [comment]
Ah, you're actually calling the function, as part of your binding declaration.

```python
bindings.append("k", None, triggerHotkey("test"))
```

I see you're trying to pass it the parameter "test" upon triggering. To do that, instead, declare like this (the 4th parameter is 'actuate_on_partial_release_flag' which should be False by default - you can read more on that in the Readme):

```python
bindings.append("k", None, triggerHotkey, False, "test")
```

Alternatively, a more explicit/readable way to make this binding would be:

```python
bindings.append({
     "hotkey": "k",
     "on_press_callback": None,
     "on_release_callback": triggerHotkey,
     "actuate_on_partial_release": False,
     "callback_params": "test"
})
```

Please let me know if that helps!

**Comment by vaylvn** [comment]
Aaaah right you are!

Apologies, amateur mistake I'm sure, just assumed I could include the argument there, didn't expect that to actually call the function itself while in a list though in hindsight that would make sense if I were calling a function to returning a value, duh,

Grand that's all been taken care of then,
Thanks!

**Comment by btsdev** [comment]
No worries! It's a common gotcha to mistakenly call a function when you're just trying to pass a reference to it. My sample code in the readme is a bit bloated in that it's trying to show off everything at once, so admittedly, it's easy to miss the nuances here.

Anyway, I'm glad you've got it sorted out!
