### ISSUE TITLE
Windows key unavailable

### ISSUE THREAD

**Issue by GerardoRodriguez19** [btsdev/global_hotkeys#5]
Hi, does the library have the ability to use Windows key to register a hotkeys? E.g. Windows + Shift + D

**Comment by btsdev** [comment]
I've not maintained this library in a long time, unfortunately. I'll try taking a look, but no promises.

Last I recall, it had issues with modifier keys (in that if you have CTRL+G as a hotkey and G as another assigned hotkey, there'd be a conflict).

**Comment by btsdev** [comment]
Ok, I've attempted to add window key support, but as you can see here on this link:

https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes

They're marked as being for "Natural Keyboards" whatever that means. I do use a special ergonomic keyboard myself (a Kinesis Advantage 2), so maybe that's related. You'll have to test for yourself to see if it worked.

That said, my personal belief is that the window/super key should be reserved for OS hotkeys only (e.g. Win+shift+left_arrow). The exception being is if you're trying to set up Hyper key shortcuts (that is, using all four modifiers at once). That's a great use case for sure; I personally use the hyper key for keybindings on VS Code. Hadn't considered it for global hotkeys.

Also, the aforementioned modifier key conflict issue is now resolved.

**Comment by btsdev** [comment]
Ah, I found the issue. There was a conflict with checking against unwanted modifier keys when accounting for "left_window", "right_window", and "window" keys. This is now fixed and working from what I've tested.

**Comment by GerardoRodriguez19** [comment]
Great, thanks for all your comments.
I appreciate it. I will test it and see how it goes
